main.py
from flask import Flask
# pip install flask
from routes.home import home_route
from routes.cliente import cliente_route


#inicializacao
app = Flask(__name__) # inicializo o flask

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')


app.run(debug=True)




# rotas
# @app.route('/')
# def ola_mundo(): # da requisicao sempre tera um returno 
#    usuarios = [
#        {'nome': 'João', 'membro_ativo': False},
#        {'nome': 'André', 'membro_ativo': True},
#        {'nome': 'Guilherme', 'membro_ativo': False}
#    ]
#    return render_template ('index.html', titulo=titulo , usuarios=usuarios)
# def pagina_sobre():
#    return """"
#        <b>Programador André<b>: Assista
#        <a href="https://www.youtube.com/watch?v=tlC90zjDCwg&list=PL39zbyHjgjrbsP3xFSc-YH-6FN8WNpglh">aqui</a>
#    """



 # estamos no modo desenvolvedor entao ele fica reinicia o servicor

routes/cliente.py
# rotas da cliente
# tenho que consultar a documentacao sempre pra fazer blueprint
#Rota de CLiente
# - /cliente/ (GET) listar os clientes
# - /cliente/ (POST) inserir um cliente
# - /cliente/new (GET) renderizar o formulario para criar um usuario
# - /cliente/<id> (GET) obter os dados de um cliente
# - /cliente/<id>/edit (GET) renderizar o formulario parar editar um cliente
# - /cliente/<id>/edit (PUT) atualizar os dados de um cliente
# - /cliente/<id>/delete (DELETE) deletar o registro do usuario



from flask import Blueprint, render_template, request
from data.cliente import CLIENTES

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route('/')
def lista_clientes():
    return render_template('lista_cliente.html', clientes=CLIENTES)


@cliente_route.route('/', methods=['POST'])
def inserir_cliente():     
    data = request.json
    novo_usuario = {
        'id': len(CLIENTES) + 1,
        'nome': data['nome'],
        'email': data['email'],
    }
    CLIENTES.append(novo_usuario)

    return render_template('item_cliente.html', cliente=novo_usuario)

       

@cliente_route.route('/new')
def form_cliente():  
    return render_template('form_cliente.html')  


@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):  
    return render_template('detalhe_cliente.html')


@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):  
       return render_template('form_edit_cliente.html')


@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_cliente(cliente_id):  
    pass    


@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):  
    pass    

routes/home.py
# rotas da pagina principal

from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/form_cliente.html
<form class="c-form" 
action="{{ url_for('cliente.inserir_cliente') }}" 
method="POST"
c-append="#lista_clientes">
    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome" >
      
    </div>
    <div class="mb-3">
        <label id="label-target" class="form-label">Email</label>
        <input type="text" class="form-control" name="email">
        
    </div>
    
    <button type="submit" class="btn btn-primary">Adicionar Cliente</button>
  </form>

templates/index.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
  </head>
  <body>
    <div class="container">
    <h1 class="text-center">Gestão de Clientes</h1>

     <div c-container="{{ url_for('cliente.form_cliente') }}"></div>  

     <hr>  

     <div c-container="{{ url_for('cliente.lista_clientes') }}" ></div>
    </div>
    
    
    


    <!--
    {% for usuario in usuarios %}
      {% if usuario.membro_ativo %}
        <div class="text-success">{{ usuario.nome }} </div>
      {% else %}
        <div class="text-danger">{{ usuario.nome }} </div>
      {% endif %}

    {% endfor %}

   instalacao do flask, criada as rotas
        uso do url_for para urls internas
        status code
        Templates html e render_template
        variaveis de contexto e logica no frontend
    -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
  </body>
</html>

templates/item_cliente.html
<tr>
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>
    <td>
        <button class="btn btn-primary">Editar</button>
        <button class="btn btn-danger">Deletar</button>
    </td>
  </tr>

templates/lista_cliente.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>

    <tbody id="lista_clientes">
    {% for cliente in clientes %}
        {% include 'item_cliente.html' %}
    {% endfor %}  
    
    </tbody>
  </table>